trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'MySelfHostedAgentPool'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'sabryfarraj/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'